# GitHub Action untuk Snake Animation
# File: .github/workflows/snake.yml

name: Generate Snake Animation

on:
  # Jalankan setiap 12 jam
  schedule:
    - cron: "0 */12 * * *"
  
  # Izinkan manual trigger
  workflow_dispatch:
  
  # Jalankan saat ada push ke main branch
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Menggunakan action untuk generate snake
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: KrisnaCahya  # Ganti dengan username GitHub Anda
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
          
      # Push hasil ke branch output
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
